language: node_js
node_js: stable

jobs:
  include:
    - stage: build
      script:
        - npm run build
        - scripts/zip_dist.sh
        - ls -la dist
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: dist/*.zip
        skip_cleanup: true
        on:
          tags: true
stages:
  - build
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
