name: Halo Admin CI

on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
  push:
    branches:
      - '**'
    paths:
      - '**'
      - '!**.md'
  release:
    types:
      - created

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint